### ISSUE TITLE
Rake fails

### ISSUE THREAD

**Issue by simonszu** [fabianonline/rubycom#1]
When executing the rake task, i get the following error:

> rake/rdoctask is deprecated.  Use rdoc/task instead (in RDoc 2.4.2+)
> rake aborted!
> uninitialized constant Rake::RDocTask
> 
> (See full trace by running task with --trace)

**Comment by simonszu** [comment]
Output with --trace:

rake/rdoctask is deprecated.  Use rdoc/task instead (in RDoc 2.4.2+)
rake aborted!
uninitialized constant Rake::RDocTask
/home/simonszu/.gem/ruby/1.9.1/gems/rake-0.9.2/lib/rake/ext/module.rb:36:in `const_missing'
/package/host/localhost/ruby-1.9.2-p180/lib/ruby/1.9.1/rdoc/task.rb:30:in`module:RDoc'
/package/host/localhost/ruby-1.9.2-p180/lib/ruby/1.9.1/rdoc/task.rb:29:in `<top (required)>'
<internal:lib/rubygems/custom_require>:29:in`require'
internal:lib/rubygems/custom_require:29:in `require'
/home/simonszu/.gem/ruby/1.9.1/gems/rake-0.9.2/lib/rake/rdoctask.rb:10:in`<top (required)>'
internal:lib/rubygems/custom_require:29:in `require'
<internal:lib/rubygems/custom_require>:29:in`require'
/var/www/virtual/simonszu/rubycom.simonszu.de/Rakefile:8:in `<top (required)>'
/home/simonszu/.gem/ruby/1.9.1/gems/rake-0.9.2/lib/rake/rake_module.rb:25:in`load'
/home/simonszu/.gem/ruby/1.9.1/gems/rake-0.9.2/lib/rake/rake_module.rb:25:in `load_rakefile'
/home/simonszu/.gem/ruby/1.9.1/gems/rake-0.9.2/lib/rake/application.rb:495:in`raw_load_rakefile'
/home/simonszu/.gem/ruby/1.9.1/gems/rake-0.9.2/lib/rake/application.rb:78:in `block in load_rakefile'
/home/simonszu/.gem/ruby/1.9.1/gems/rake-0.9.2/lib/rake/application.rb:129:in`standard_exception_handling'
/home/simonszu/.gem/ruby/1.9.1/gems/rake-0.9.2/lib/rake/application.rb:77:in `load_rakefile'
/home/simonszu/.gem/ruby/1.9.1/gems/rake-0.9.2/lib/rake/application.rb:61:in`block in run'
/home/simonszu/.gem/ruby/1.9.1/gems/rake-0.9.2/lib/rake/application.rb:129:in `standard_exception_handling'
/home/simonszu/.gem/ruby/1.9.1/gems/rake-0.9.2/lib/rake/application.rb:59:in`run'
/home/simonszu/.gem/ruby/1.9.1/gems/rake-0.9.2/bin/rake:32:in `<top (required)>'
/home/simonszu/.gem/ruby/1.9.1/bin/rake:19:in`load'
/home/simonszu/.gem/ruby/1.9.1/bin/rake:19:in `<main>'

Seems the problem is: You developed for ruby 1.8, i use 1.9

**Comment by simonszu** [comment]
I have installed RVM now, and also Ruby1.8.6. I used your .rvmrc and installed Rails 2.8.6 and the latest version of rake. The Output of ''rake db:migrate'' is now:

NOTE: Gem.source_index is deprecated, use Specification. It will be removed on or after 2011-11-01.
Gem.source_index called from /var/www/virtual/simonszu/rubycom.simonszu.de/config/../vendor/rails/railties/lib/rails/gem_dependency.rb:21.
NOTE: Gem::SourceIndex#refresh! is deprecated with no replacement. It will be removed on or after 2011-11-01.
Gem::SourceIndex#refresh! called from /var/www/virtual/simonszu/rubycom.simonszu.de/config/../vendor/rails/railties/lib/rails/vendor_gem_source_index.rb:34.
NOTE: Gem::SourceIndex#load_gems_in is deprecated with no replacement. It will be removed on or after 2011-11-01.
Gem::SourceIndex#load_gems_in called from /home/simonszu/.rvm/rubies/ruby-1.8.7-p352/lib/ruby/site_ruby/1.8/rubygems/source_index.rb:322.
NOTE: Gem::SourceIndex#add_spec is deprecated, use Specification.add_spec. It will be removed on or after 2011-11-01.
Gem::SourceIndex#add_spec called from /home/simonszu/.rvm/rubies/ruby-1.8.7-p352/lib/ruby/site_ruby/1.8/rubygems/source_index.rb:127.
NOTE: Gem::SourceIndex#add_spec is deprecated, use Specification.add_spec. It will be removed on or after 2011-11-01.
Gem::SourceIndex#add_spec called from /home/simonszu/.rvm/rubies/ruby-1.8.7-p352/lib/ruby/site_ruby/1.8/rubygems/source_index.rb:127.
NOTE: Gem::SourceIndex#add_spec is deprecated, use Specification.add_spec. It will be removed on or after 2011-11-01.
Gem::SourceIndex#add_spec called from /home/simonszu/.rvm/rubies/ruby-1.8.7-p352/lib/ruby/site_ruby/1.8/rubygems/source_index.rb:127.
NOTE: Gem::SourceIndex#add_spec is deprecated, use Specification.add_spec. It will be removed on or after 2011-11-01.
Gem::SourceIndex#add_spec called from /home/simonszu/.rvm/rubies/ruby-1.8.7-p352/lib/ruby/site_ruby/1.8/rubygems/source_index.rb:127.
NOTE: Gem::SourceIndex#add_spec is deprecated, use Specification.add_spec. It will be removed on or after 2011-11-01.
Gem::SourceIndex#add_spec called from /home/simonszu/.rvm/rubies/ruby-1.8.7-p352/lib/ruby/site_ruby/1.8/rubygems/source_index.rb:127.
NOTE: Gem::SourceIndex#add_spec is deprecated, use Specification.add_spec. It will be removed on or after 2011-11-01.
Gem::SourceIndex#add_spec called from /home/simonszu/.rvm/rubies/ruby-1.8.7-p352/lib/ruby/site_ruby/1.8/rubygems/source_index.rb:127.
NOTE: Gem::SourceIndex#add_spec is deprecated, use Specification.add_spec. It will be removed on or after 2011-11-01.
Gem::SourceIndex#add_spec called from /home/simonszu/.rvm/rubies/ruby-1.8.7-p352/lib/ruby/site_ruby/1.8/rubygems/source_index.rb:127.
NOTE: Gem::SourceIndex#add_spec is deprecated, use Specification.add_spec. It will be removed on or after 2011-11-01.
Gem::SourceIndex#add_spec called from /home/simonszu/.rvm/rubies/ruby-1.8.7-p352/lib/ruby/site_ruby/1.8/rubygems/source_index.rb:127.
NOTE: Gem::SourceIndex#initialize is deprecated with no replacement. It will be removed on or after 2011-11-01.
Gem::SourceIndex#initialize called from /var/www/virtual/simonszu/rubycom.simonszu.de/config/../vendor/rails/railties/lib/rails/vendor_gem_source_index.rb:100.
NOTE: Gem::SourceIndex#add_spec is deprecated, use Specification.add_spec. It will be removed on or after 2011-11-01.
Gem::SourceIndex#add_spec called from /home/simonszu/.rvm/rubies/ruby-1.8.7-p352/lib/ruby/site_ruby/1.8/rubygems/source_index.rb:91.
NOTE: Gem::SourceIndex#add_spec is deprecated, use Specification.add_spec. It will be removed on or after 2011-11-01.
Gem::SourceIndex#add_spec called from /home/simonszu/.rvm/rubies/ruby-1.8.7-p352/lib/ruby/site_ruby/1.8/rubygems/source_index.rb:91.
NOTE: Gem::SourceIndex#add_spec is deprecated, use Specification.add_spec. It will be removed on or after 2011-11-01.
Gem::SourceIndex#add_spec called from /home/simonszu/.rvm/rubies/ruby-1.8.7-p352/lib/ruby/site_ruby/1.8/rubygems/source_index.rb:91.
NOTE: Gem::SourceIndex#add_spec is deprecated, use Specification.add_spec. It will be removed on or after 2011-11-01.
Gem::SourceIndex#add_spec called from /home/simonszu/.rvm/rubies/ruby-1.8.7-p352/lib/ruby/site_ruby/1.8/rubygems/source_index.rb:91.
NOTE: Gem::SourceIndex#add_spec is deprecated, use Specification.add_spec. It will be removed on or after 2011-11-01.
Gem::SourceIndex#add_spec called from /home/simonszu/.rvm/rubies/ruby-1.8.7-p352/lib/ruby/site_ruby/1.8/rubygems/source_index.rb:91.
NOTE: Gem::SourceIndex#add_spec is deprecated, use Specification.add_spec. It will be removed on or after 2011-11-01.
Gem::SourceIndex#add_spec called from /home/simonszu/.rvm/rubies/ruby-1.8.7-p352/lib/ruby/site_ruby/1.8/rubygems/source_index.rb:91.
rake/rdoctask is deprecated.  Use rdoc/task instead (in RDoc 2.4.2+)
rake aborted!
uninitialized constant ActiveSupport::Dependencies::Mutex

(See full trace by running task with --trace)

**Comment by fabianonline** [comment]
Possible fixes:
- Add `require 'thread'` to the top of boot.rb
- Try using Rails 2.3.11

**Comment by fabianonline** [comment]
Try the newest version. It should use Rails 2.3.11. Gems are correctly defined in config/environment.rb (including their versions) and can be installed by `rake gems:install` (or just be displayed by `rake gems`).

**Comment by simonszu** [comment]
I'll do it. 
Wouldn't it be nice to commit a database.yml with just the "production" section, so it is more end-user-friendly (besides that, FastCGI does not use different environments)?

Hang on while i am contacting my hoster to install imagemagick :P

**Comment by fabianonline** [comment]
Nope. That database.yml-layout is the default from RoR. But indeed I could expand the documentation to stress this point.

**Comment by simonszu** [comment]
Yes, indeed. Especially the testing environment can cause problems. 

Well, now i have a problem, i mentioned on twitter before. Rake can't find Rmagick. The output of `gem list` is as following:

**\* LOCAL GEMS ***

actionmailer (2.3.11)
actionpack (2.3.11)
activerecord (2.3.11)
activeresource (2.3.11)
activesupport (2.3.11)
bundle (0.0.1)
bundler (1.0.21)
multi_json (1.0.3)
nokogiri (1.4.4)
rack (1.1.2)
rails (2.3.11)
rake (0.9.2)
rmagick (2.13.1)

The last few lines of `rake db:migrate` are:
/home/simonszu/.rvm/gems/ruby-1.8.6-p420@rubycom/bin/rake:19
Missing these required gems:
  rmagick  = 2.13.1

You're running:
  ruby 1.8.6.420 at /home/simonszu/.rvm/rubies/ruby-1.8.6-p420/bin/ruby
  rubygems 1.3.7 at /home/simonszu/.rvm/gems/ruby-1.8.6-p420@rubycom, /home/simonszu/.rvm/gems/ruby-1.8.6-p420@global

Run `rake gems:install` to install the missing gems.

Just for testing, i executed `rake gems:install` and the output is this one:
rake/rdoctask is deprecated.  Use rdoc/task instead (in RDoc 2.4.2+)
DEPRECATION WARNING: Rake tasks in vendor/plugins/jrails/tasks are deprecated. Use lib/tasks instead. (called from /home/simonszu/.rvm/gems/ruby-1.8.6-p420@rubycom/gems/rails-2.3.11/lib/tasks/rails.rb:10)

But this is the "prelude" i get from every rake task within this rvm environment.

**Comment by simonszu** [comment]
I pulled it again. The Output of `rake gems` is now:

rake aborted!
no such file to load -- rdoc/task

(See full trace by running task with --trace)

The same is when executing `rake db:migrate`

**Comment by fabianonline** [comment]
Meh. Okay, please pull and try again... -.-

**Comment by simonszu** [comment]
Same error again.

**Comment by simonszu** [comment]
After `gem install rdoc -v=3.9.4` a `rake gems` leads to this output:

rake aborted!
undefined method `name' for "actionmailer":String

Tasks: TOP => environment
(See full trace by running task with --trace)

**Comment by simonszu** [comment]
well, the db migrating works fine when i uncomment the 'require rmagick' line from environment.rb.

I am running the App with passenger standalone and an apache rewrite rule. The passenger does not start when rmagick is required, because he can't find it, too.

When starting the app without rmagick, i get the following error: http://rubycom.simonszu.de

**Comment by fabianonline** [comment]
Resolved. Issue was caused by a botched installation of RMagick.
