### ISSUE TITLE
Feed not showing any content

### ISSUE THREAD

**Issue by simonszu** [fabianonline/rubycom#10]
Hi,

yesterday i decided to add the feed to my feed reader. It updated, and there were comics to read.
Today, i refreshed the feed, but no new items showed up. But there are definitely new items, as i can see in the web frontend.

**Comment by fabianonline** [comment]
Seems to be some kind of overdone nitpickyness of Google Reader... (Hopefully) Fixed in commit 40160b916bbbed98cf687a4d9e12a180f584c1cd
